import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
import FooterWithSocialMediaIcons, { Footer } from '@/components/FooterWithSocialMediaIcons'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Horacio Andrade',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
        <FooterWithSocialMediaIcons/>        
        </body>
    </html>
  )
}
